controllers:
   - name: 'eband'
     type: 'eband_local_planner/EBandPlannerROS'
   - name: 'dwa'
     type: 'dwa_local_planner/DWAPlannerROS'
eband:
  Ctrl_Rate: 20.0
  bubble_velocity_multiplier: 2.0
  costmap_weight: 10.0
  differential_drive: true
  disallow_hysteresis: false
  eband_equilibrium_approx_max_recursion_depth: 3
  eband_equilibrium_relative_overshoot: 0.75
  eband_external_force_gain: 3.0
  eband_internal_force_gain: 2.0
  eband_min_relative_overlap: 0.7
  eband_significant_force_lower_bound: 0.15
  eband_tiny_bubble_distance: 0.01
  eband_tiny_bubble_expansion: 0.01
  in_place_trans_vel: 0.0
  k_damp: 3.5
  k_prop: 4.0
  marker_lifetime: 0.5
  max_acceleration: 0.2
  max_rotational_acceleration: 0.3
  max_translational_acceleration: 0.4
  # Lower values for testing with the actual robot.
  max_vel_lin: 1.1 #0.5 #1.45
  max_vel_th: 1.2 #0.5 #2.0
  min_in_place_vel_th: 0.05
  min_vel_lin: 0.0
  min_vel_th: 0.0
  num_iterations_eband_optimization: 4
  rot_stopped_vel: 0.01
  rotation_correction_threshold: 0.5
  rotation_threshold_multiplier: 1.0
  trans_stopped_vel: 0.01
  virtual_mass: 100.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

dwa:
  max_vel_x: 2.0
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 2.12
  min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.1

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_rot_vel: 2.0  # choose slightly less than the base's capability
  min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.1

  acc_lim_x: 0.7 # maximum is theoretically 2.0, but we
  acc_lim_theta: 10.0
  acc_lim_y: 0.1      # diff drive robot

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.4  # 0.05
  xy_goal_tolerance: 0.2   # 0.10
  # latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0       # 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 20      # 3
  vy_samples: 1       # diff drive robot, there is only one sample
  vtheta_samples: 20  # 20

  # Trajectory Scoring Parameters
  path_distance_bias: 0.1      # 32.0   - weighting for how much it should stick to the global path plan -- if this value is too high, won't avoid dynamic obstacles
  goal_distance_bias: 40.0     # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.2           # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.0  # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.3        # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 1.0           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2      # 0.2    - how much to scale the robot's footprint when at speed.

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.1  # 0.05   - how far to travel before resetting oscillation flags

  holonomic_robot: false

    # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: map

